### ISSUE TITLE
`cell_locations` fails when `augmented_metadata_output` is on S3

### ISSUE THREAD

**Issue by shntnu** [cytomining/pycytominer#270]
```
python -m pycytominer.cyto_utils.cell_locations_cmd --metadata_input s3://cellpainting-gallery/cpg0016-jump/source_7/workspace/load_data_csv/20211211_Run9M/CP7-SC1-03/load_data_with_illum.parquet --single_cell_input s3://cellpainting-gallery/cpg0016-jump/source_7/workspace/backend/20211211_Run9M/CP7-SC1-03/CP7-SC1-03.sqlite --augmented_metadata_output s3://cellpainting-gallery/cpg0016-jump/source_7/workspace/load_data_csv/20211211_Run9M/CP7-SC1-03/load_data_with_illum_and_cell_location.parquet add_cell_location
Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/envs/datasets-private/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/mambaforge/envs/datasets-private/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/mambaforge/envs/datasets-private/lib/python3.10/site-packages/pycytominer/cyto_utils/cell_locations_cmd.py", line 5, in <module>
    fire.Fire(CellLocation)
  File "/home/ubuntu/mambaforge/envs/datasets-private/lib/python3.10/site-packages/fire/core.py", line 141, in Fire    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/mambaforge/envs/datasets-private/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ubuntu/mambaforge/envs/datasets-private/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/mambaforge/envs/datasets-private/lib/python3.10/site-packages/pycytominer/cyto_utils/cell_locations.py", line 407, in add_cell_location
    and self._s3_file_exists(self.augmented_metadata_output)
  File "/home/ubuntu/mambaforge/envs/datasets-private/lib/python3.10/site-packages/pycytominer/cyto_utils/cell_locations.py", line 150, in _s3_file_exists
    self.s3.Object(bucket, key).load()
  File "/home/ubuntu/mambaforge/envs/datasets-private/lib/python3.10/site-packages/botocore/client.py", line 876, in __getattr__    raise AttributeError(AttributeError: 'S3' object has no attribute 'Object'
```

**Comment by shntnu** [comment]
Fixed in #271
