### ISSUE TITLE
Bug in annotate

### ISSUE THREAD

**Issue by ErinWeisbart** [cytomining/pycytominer#284]
```
Now processing... batch: 2023_05_04_Pilot
Now annotating... plate: CPmGluePilotU2OS
Traceback (most recent call last):
  File "profiling-recipe/profiles/profiling_pipeline.py", line 34, in <module>
    run_pipeline.pipeline_annotate(batch=batch, plate=plate)
  File "/home/ubuntu/work/projects/2023_05_04_mGlueCP_AD/workspace/software/2023_05_04_mGlueCP_AD/profiling-recipe/profiles/profile.py", line 160, in pipeline_annotate
    annotate(
  File "/home/ubuntu/ebs_tmp/2023_05_04_mGlueCP_AD/workspace/software/pycytominer/pycytominer/annotate.py", line 77, in annotate
    profiles = load_profiles(profiles)
  File "/home/ubuntu/ebs_tmp/2023_05_04_mGlueCP_AD/workspace/software/pycytominer/pycytominer/cyto_utils/load.py", line 94, in load_profiles
    if is_path_a_parquet_file(profiles):
  File "/home/ubuntu/ebs_tmp/2023_05_04_mGlueCP_AD/workspace/software/pycytominer/pycytominer/cyto_utils/load.py", line 35, in is_path_a_parquet_file
    raise TypeError(f"file must be a str or pathlib.Path not {type(file)}")
TypeError: file must be a str or pathlib.Path not <class 'pathlib.PurePosixPath'>
```
  
  
If I jump back to 5c15711 then it works fine. Didn't dig deeper than that.

**Comment by gwaybio** [comment]
fixed in #285 - thanks for documenting this @ErinWeisbart !
