### ISSUE TITLE
gzip fails csv sniffer

### ISSUE THREAD

**Issue by gwaygenomics** [cytomining/pycytominer#95]
The file delimiter sniffer addition gets the following error when reading in a gzip file.

```python
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-5-c59d302735b0> in <module>
     16         output_file=output_file,
     17         compression=compression,
---> 18         float_format=float_format,
     19     )

~/miniconda3/envs/pooled-cell-painting/lib/python3.7/site-packages/pycytominer/normalize.py in normalize(profiles, features, meta_features, samples, method, output_file, compression, float_format, whiten_center)
     56 
     57     # Load Data
---> 58     profiles = load_profiles(profiles)
     59 
     60     # Define which scaler to use

~/miniconda3/envs/pooled-cell-painting/lib/python3.7/site-packages/pycytominer/cyto_utils/load.py in load_profiles(profiles)
     31     if not isinstance(profiles, pd.DataFrame):
     32         try:
---> 33             delim = infer_delim(profiles)
     34             profiles = pd.read_csv(profiles, sep=delim)
     35         except FileNotFoundError:

~/miniconda3/envs/pooled-cell-painting/lib/python3.7/site-packages/pycytominer/cyto_utils/load.py in infer_delim(file)
     14     """
     15     with open(file) as csvfile:
---> 16         dialect = csv.Sniffer().sniff(csvfile.readline())
     17 
     18     return(dialect.delimiter)

~/miniconda3/envs/pooled-cell-painting/lib/python3.7/codecs.py in decode(self, input, final)
    320         # decode input (taking the buffer into account)
    321         data = self.buffer + input
--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
    323         # keep undecoded input until the next call
    324         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by gwaygenomics** [comment]
this came up again in a high leverage situation (processing resistance mechanisms profiles) and requires immediate attention.

**Comment by gwaygenomics** [comment]
```python
Now processing... batch: 2020_08_24_Batch9, plate: 218696
Traceback (most recent call last):
  File "generate-profiles.py", line 27, in <module>
    process_profile(sql_file=sql_file, batch=batch, plate=plate, pipeline=pipeline)
  File "/home/ubuntu/efs/2018_05_30_ResistanceMechanisms_Kapoor/workspace/software/2018_05_30_ResistanceMechanisms_Kapoor/0.generate-profiles/scripts/profile_util.py", line 168, in process_profile
    compression=compression,
  File "/home/ubuntu/miniconda3/envs/resistance-mechanisms/lib/python3.7/site-packages/pycytominer/annotate.py", line 60, in annotate
    profiles = load_profiles(profiles)
  File "/home/ubuntu/miniconda3/envs/resistance-mechanisms/lib/python3.7/site-packages/pycytominer/cyto_utils/load.py", line 33, in load_profiles
    delim = infer_delim(profiles)
  File "/home/ubuntu/miniconda3/envs/resistance-mechanisms/lib/python3.7/site-packages/pycytominer/cyto_utils/load.py", line 16, in infer_delim
    dialect = csv.Sniffer().sniff(csvfile.readline())
  File "/home/ubuntu/miniconda3/envs/resistance-mechanisms/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```
